{
  "formatVersion": "1.1",
  "component": {
    "group": "com.wzz",
    "module": "w-loader-api",
    "version": "1.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "w-loader-api-1.3.jar",
          "url": "w-loader-api-1.3.jar",
          "size": 452976,
          "sha512": "a2e2779c5521e47a282dc1997cae8ea638356da9c34fe503b2a71b8c11b6e3fac37b1c71e75f1db76079d7e9b57ed496bfd14eb1940a693df3a311a376807657",
          "sha256": "2fd5e354046db0fa1abacc3cb9e083544d7e2ce35f85b4e6dfa399f63e1d6a0f",
          "sha1": "479223fcaa1f192ec394f8693389c62882d725e8",
          "md5": "e2b2f3bedee54291ea2fc192f5448515"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "w-loader-api-1.3.jar",
          "url": "w-loader-api-1.3.jar",
          "size": 452976,
          "sha512": "a2e2779c5521e47a282dc1997cae8ea638356da9c34fe503b2a71b8c11b6e3fac37b1c71e75f1db76079d7e9b57ed496bfd14eb1940a693df3a311a376807657",
          "sha256": "2fd5e354046db0fa1abacc3cb9e083544d7e2ce35f85b4e6dfa399f63e1d6a0f",
          "sha1": "479223fcaa1f192ec394f8693389c62882d725e8",
          "md5": "e2b2f3bedee54291ea2fc192f5448515"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "w-loader-api-1.3-sources.jar",
          "url": "w-loader-api-1.3-sources.jar",
          "size": 435659,
          "sha512": "1321f6d90a23bdb356628442c0b3b73c497d65a9a85fcb74bd67870f3088f6559b1bd1e8d9d1c38d700245fd7abfb37c3b101765f0d1687821ea6e66811b9ed6",
          "sha256": "92e2d294f71e9abb8b6e1d0254f90832ac046e3b98c5232804e92d55900ae1c1",
          "sha1": "416a3569d16ca781ebe4f0609b47345042631a48",
          "md5": "91bbdbc8ac1933b54f0f7c2b8abf28db"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "w-loader-api-1.3-javadoc.jar",
          "url": "w-loader-api-1.3-javadoc.jar",
          "size": 5148966,
          "sha512": "e8664e2d26199321b804716770e6719e75e3c2374f33a64b479e099cb34ccfbdf3a93f64a2f8a7685f470a1465fc05d65a230fc7b2c7bbc156fb7bcbb00cb4de",
          "sha256": "7fb57c8b32566cf92268a4822b1ebca81a0d270efa787d05d8369508dfe5e43a",
          "sha1": "1c3334a78c5c1d6e122e25c9f146a5bfd799c661",
          "md5": "ad9473330db01aca98ac66d33041f8b0"
        }
      ]
    }
  ]
}
