{
  "formatVersion": "1.1",
  "component": {
    "group": "com.wzz",
    "module": "w-loader-api",
    "version": "1.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "w-loader-api-1.3.jar",
          "url": "w-loader-api-1.3.jar",
          "size": 450753,
          "sha512": "2ebd391f53ef73ea923e79e9b1414e752a248241a15f8b9d6baa26b956dbf5d3a2c98eb6c9f9aed5681866c2a33674e6e937c4c59b8423e951123c38472aeec2",
          "sha256": "c93ccb35175d7ede78d21fa1397f353a6f4bdc0932cb5efaabd5b78b5a43e539",
          "sha1": "c12bdb3c1a5f58d3d2caadccb67cf5e0ee757833",
          "md5": "4a52edf0ee15fae234b4051c7066168a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "w-loader-api-1.3.jar",
          "url": "w-loader-api-1.3.jar",
          "size": 450753,
          "sha512": "2ebd391f53ef73ea923e79e9b1414e752a248241a15f8b9d6baa26b956dbf5d3a2c98eb6c9f9aed5681866c2a33674e6e937c4c59b8423e951123c38472aeec2",
          "sha256": "c93ccb35175d7ede78d21fa1397f353a6f4bdc0932cb5efaabd5b78b5a43e539",
          "sha1": "c12bdb3c1a5f58d3d2caadccb67cf5e0ee757833",
          "md5": "4a52edf0ee15fae234b4051c7066168a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "w-loader-api-1.3-sources.jar",
          "url": "w-loader-api-1.3-sources.jar",
          "size": 434447,
          "sha512": "d4a096083732a6221f3f0c96f5262e326e309df667fcf5abec8fdc0489a6736c83c6e038f57bd51eafa647b2703146dd3e2181e7ee89e0a54076d98e7868ff70",
          "sha256": "4942728380ee1644e0f8bf19ba51e478ee234c870f840ac0c93a882ed30e143a",
          "sha1": "e646a7914880e9426f8e55b0e89fa79a64a2a10f",
          "md5": "575ba61fbd21d07c06e9ce287ee7caf0"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "w-loader-api-1.3-javadoc.jar",
          "url": "w-loader-api-1.3-javadoc.jar",
          "size": 5148825,
          "sha512": "2708e50b17944a0f8920c36a8e55cc683d9139e5b925682eeeb7d42f8722bfc4a8812a2c756edd41348dfb7afb26e1856b56ed079cb7dd9dd2f615ef40a3d85c",
          "sha256": "917b6689276b0feda427ddfbac4fd6a2674140038a3569a74ae0318758e1ed3f",
          "sha1": "a277baee0c7696630c1948df9f6f2d176f2d4bf5",
          "md5": "a48dc7760c514aa52c8db04ce47581ee"
        }
      ]
    }
  ]
}
