{
  "formatVersion": "1.1",
  "component": {
    "group": "com.wzz",
    "module": "w-loader-api",
    "version": "1.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "w-loader-api-1.3.jar",
          "url": "w-loader-api-1.3.jar",
          "size": 450755,
          "sha512": "dcf8764302e98814a6561c402aa0a00e24f2e4d8006c318801b32f36b44688019dda8b6c7f60e0d44461caae1defe522ac7805633d5bdc18353e2f2c09c7d0a0",
          "sha256": "6860fb7aa5b5ae8aebb23f61f198702b59e5ce162e5d297a07bd267320640548",
          "sha1": "d48f7cce3537c363ca4a697cec7ac25b56ccd68d",
          "md5": "96eba39995b97e151b39673cb79997b1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "w-loader-api-1.3.jar",
          "url": "w-loader-api-1.3.jar",
          "size": 450755,
          "sha512": "dcf8764302e98814a6561c402aa0a00e24f2e4d8006c318801b32f36b44688019dda8b6c7f60e0d44461caae1defe522ac7805633d5bdc18353e2f2c09c7d0a0",
          "sha256": "6860fb7aa5b5ae8aebb23f61f198702b59e5ce162e5d297a07bd267320640548",
          "sha1": "d48f7cce3537c363ca4a697cec7ac25b56ccd68d",
          "md5": "96eba39995b97e151b39673cb79997b1"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "w-loader-api-1.3-sources.jar",
          "url": "w-loader-api-1.3-sources.jar",
          "size": 434480,
          "sha512": "ae3f6b229d99444a69d55d69e12c7e56d39c97ace18235eec5b404ad057863f09b950b8212c8390f2fe4a0d945ec8db00f1ad7bd9fb471f32fdee9cafe232ac8",
          "sha256": "99bebe6defd9efa6fb2a5e0c9ee2095660113b21cfb06cf8d5778ad931b71aa4",
          "sha1": "c950473cf501cb75360bb308e458e122de812db6",
          "md5": "47c863dfd11e95a6e501486ef2517ea8"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "w-loader-api-1.3-javadoc.jar",
          "url": "w-loader-api-1.3-javadoc.jar",
          "size": 5148825,
          "sha512": "2708e50b17944a0f8920c36a8e55cc683d9139e5b925682eeeb7d42f8722bfc4a8812a2c756edd41348dfb7afb26e1856b56ed079cb7dd9dd2f615ef40a3d85c",
          "sha256": "917b6689276b0feda427ddfbac4fd6a2674140038a3569a74ae0318758e1ed3f",
          "sha1": "a277baee0c7696630c1948df9f6f2d176f2d4bf5",
          "md5": "a48dc7760c514aa52c8db04ce47581ee"
        }
      ]
    }
  ]
}
